### ISSUE TITLE
Workflow creation not idempotent

### ISSUE THREAD

**Issue by myllynen** [redhat-cop/automate_tower_genie_collections#1243]
A workflow definition like this seems to always cause changes reported for some reason:

```
controller_workflows:
  - name: Test Workflow Job Template
    description: Workflow for testing
    organization: Test Org
    inventory: Test Inventory
    limit: local
    extra_vars:
      message: Message from workflow
    simplified_workflow_nodes:
      - identifier: node1
        all_parents_must_converge: false
        unified_job_template: Test Random Failure
        credentials: []
        success_nodes:
          - node10
        failure_nodes:
          - node20
        always_nodes: []
      - identifier: node10
        approval_node:
          name: Test Approval
          description: Approval step for testing
          timeout: 0
        success_nodes:
          - node11
      - identifier: node11
        unified_job_template: Test Job Template
      - identifier: node20
        unified_job_template: Test Random Failure
```

With AAP 2.6-3 and ansible.platform 2.6.20251106:

```
TASK [infra.aap_configuration.controller_workflow_job_templates : add_workflows_schema | Create links between Workflow Nodes]
changed: [localhost] => (item=node1)
changed: [localhost] => (item=node10)
skipping: [localhost] => (item=node11) 
skipping: [localhost] => (item=node20) 
```

Not sure if this is due to infra.aap_collection but perhaps easiest to check here first. Thanks.

**Comment by djdanielsson** [comment]
This is a module issue, not related to our code

**Comment by djdanielsson** [comment]
We've investigated this issue against the latest `ansible.controller` collection (v4.7.9). The `modify_associations` method in `controller_api.py` now includes idempotency logic that compares existing association IDs with the desired ones using set comparison and returns early without making changes when they match:

```python
if set(existing_associated_ids) == set(new_association_list):
    return
```

Since `always_nodes`, `success_nodes`, and `failure_nodes` are not in the `ordered_associations` list, they use this set-based comparison which should prevent false `changed` reports.

We believe this has been fixed in the latest version of the `ansible.controller` collection. Could you please upgrade to `ansible.controller >= 4.7.9` and test again? If the issue persists, please reopen with updated details.

**Comment by myllynen** [comment]
I still see the issue with ansible.controller 4.7.9 (and ansible.platform 2.6.20260306). It's still the "Create links between Workflow Nodes" task that is always reporting changes, some ~200 other tasks all around are correctly reporting no changes.

I don't have permissions to reopen this issue. Thanks.
